/* eslint-disable max-len */
/* eslint-disable max-lines */
/* eslint-disable max-lines-per-function */
import { QueryInterface } from 'sequelize';

export default {

  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert(
      'meals',
      [
        {
          strMeal: 'Moussaka',
          strDrinkAlternate: null,
          strCategoryId: 1,
          strAreaId: 10,
          strInstructions: 'Heat the grill to high.',
          strMealThumb: 'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
          strTags: null,
          strYoutube: 'https://www.youtube.com/watch?v=8U_29i9Qp5U',
          strIngredient1Id: 1,
          strIngredient2Id: 2,
          strIngredient3Id: 3,
          strIngredient4Id: null,
          strIngredient5Id: null,
          strIngredient6Id: null,
          strIngredient7Id: null,
          strIngredient8Id: null,
          strIngredient9Id: null,
          strIngredient10Id: null,
          strIngredient11Id: null,
          strIngredient12Id: null,
          strIngredient13Id: null,
          strIngredient14Id: null,
          strIngredient15Id: null,
          strIngredient16Id: null,
          strIngredient17Id: null,
          strIngredient18Id: null,
          strIngredient19Id: null,
          strIngredient20Id: null,
          strMeasure1: 'Dash',
          strMeasure2: '1 Can',
          strMeasure3: '3 thin cut',
          strMeasure4: null,
          strMeasure5: null,
          strMeasure6: null,
          strMeasure7: null,
          strMeasure8: null,
          strMeasure9: null,
          strMeasure10: null,
          strMeasure11: null,
          strMeasure12: null,
          strMeasure13: null,
          strMeasure14: null,
          strMeasure15: null,
          strMeasure16: null,
          strMeasure17: null,
          strMeasure18: null,
          strMeasure19: null,
          strMeasure20: null,
          strSource: 'https://www.bbcgoodfood.com/recipes/must-make-moussaka',
          strImageSource: null,
          strCreativeCommonsConfirmed: null,
          dateModified: null,
        },
        {
          strMeal: 'Shawarma',
          strDrinkAlternate: null,
          strCategoryId: 2,
          strAreaId: 3,
          strInstructions: 'Combine the marinade ingredients in a large ziplock bag (or bowl).',
          strMealThumb: 'https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg',
          strTags: null,
          strYoutube: 'https://www.youtube.com/watch?v=3lxUIeKDgic',
          strIngredient1Id: 1,
          strIngredient2Id: 2,
          strIngredient3Id: 3,
          strIngredient4Id: null,
          strIngredient5Id: null,
          strIngredient6Id: null,
          strIngredient7Id: null,
          strIngredient8Id: null,
          strIngredient9Id: null,
          strIngredient10Id: null,
          strIngredient11Id: null,
          strIngredient12Id: null,
          strIngredient13Id: null,
          strIngredient14Id: null,
          strIngredient15Id: null,
          strIngredient16Id: null,
          strIngredient17Id: null,
          strIngredient18Id: null,
          strIngredient19Id: null,
          strIngredient20Id: null,
          strMeasure1: 'Dash',
          strMeasure2: '1 Can',
          strMeasure3: '4 thin cut',
          strMeasure4: null,
          strMeasure5: null,
          strMeasure6: null,
          strMeasure7: null,
          strMeasure8: null,
          strMeasure9: null,
          strMeasure10: null,
          strMeasure11: null,
          strMeasure12: null,
          strMeasure13: null,
          strMeasure14: null,
          strMeasure15: null,
          strMeasure16: null,
          strMeasure17: null,
          strMeasure18: null,
          strMeasure19: null,
          strMeasure20: null,
          strSource: 'https://www.recipetineats.com/chicken-sharwama-middle-eastern/',
          strImageSource: null,
          strCreativeCommonsConfirmed: null,
          dateModified: null,
        },
        {
          strMeal: 'Timbits',
          strDrinkAlternate: null,
          strCategoryId: 3,
          strAreaId: 7,
          strInstructions: 'Sift together dry ingredients.\r\nMix together wet ingredients and incorporate into dry.',
          strMealThumb: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
          strTags: 'Snack,Treat',
          strYoutube: 'https://www.youtube.com/watch?v=fFLn1h80AGQ',
          strIngredient1Id: 1,
          strIngredient2Id: 2,
          strIngredient3Id: 3,
          strIngredient4Id: null,
          strIngredient5Id: null,
          strIngredient6Id: null,
          strIngredient7Id: null,
          strIngredient8Id: null,
          strIngredient9Id: null,
          strIngredient10Id: null,
          strIngredient11Id: null,
          strIngredient12Id: null,
          strIngredient13Id: null,
          strIngredient14Id: null,
          strIngredient15Id: null,
          strIngredient16Id: null,
          strIngredient17Id: null,
          strIngredient18Id: null,
          strIngredient19Id: null,
          strIngredient20Id: null,
          strMeasure1: 'Dash',
          strMeasure2: '1 Can',
          strMeasure3: '2 thin cut',
          strMeasure4: null,
          strMeasure5: null,
          strMeasure6: null,
          strMeasure7: null,
          strMeasure8: null,
          strMeasure9: null,
          strMeasure10: null,
          strMeasure11: null,
          strMeasure12: null,
          strMeasure13: null,
          strMeasure14: null,
          strMeasure15: null,
          strMeasure16: null,
          strMeasure17: null,
          strMeasure18: null,
          strMeasure19: null,
          strMeasure20: null,
          strSource: 'http://www.geniuskitchen.com/recipe/drop-doughnuts-133877',
          strImageSource: null,
          strCreativeCommonsConfirmed: null,
          dateModified: null,
        },
        {
          strMeal: 'Kapsalon',
          strDrinkAlternate: null,
          strCategoryId: 4,
          strAreaId: 9,
          strInstructions: 'Cut the meat into strips. Heat oil in a pan and fry the strips for 6 minutes until it\'s ready.',
          strMealThumb: 'https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg',
          strTags: 'Snack',
          strYoutube: 'https://www.youtube.com/watch?v=UIcuiU1kV8I',
          strIngredient1Id: 1,
          strIngredient2Id: 2,
          strIngredient3Id: 3,
          strIngredient4Id: null,
          strIngredient5Id: null,
          strIngredient6Id: null,
          strIngredient7Id: null,
          strIngredient8Id: null,
          strIngredient9Id: null,
          strIngredient10Id: null,
          strIngredient11Id: null,
          strIngredient12Id: null,
          strIngredient13Id: null,
          strIngredient14Id: null,
          strIngredient15Id: null,
          strIngredient16Id: null,
          strIngredient17Id: null,
          strIngredient18Id: null,
          strIngredient19Id: null,
          strIngredient20Id: null,
          strMeasure1: 'Dash',
          strMeasure2: '1 Can',
          strMeasure3: '5 thin cut',
          strMeasure4: null,
          strMeasure5: null,
          strMeasure6: null,
          strMeasure7: null,
          strMeasure8: null,
          strMeasure9: null,
          strMeasure10: null,
          strMeasure11: null,
          strMeasure12: null,
          strMeasure13: null,
          strMeasure14: null,
          strMeasure15: null,
          strMeasure16: null,
          strMeasure17: null,
          strMeasure18: null,
          strMeasure19: null,
          strMeasure20: null,
          strSource: null,
          strImageSource: null,
          strCreativeCommonsConfirmed: null,
          dateModified: null,
        },
        {
          strMeal: 'Poutine',
          strDrinkAlternate: null,
          strCategoryId: 5,
          strAreaId: 15,
          strInstructions: 'Heat oil in a deep fryer or deep heavy skillet to 365\u00b0F (185\u00b0C).',
          strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
          strTags: 'UnHealthy,Speciality,HangoverFood',
          strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
          strIngredient1Id: 1,
          strIngredient2Id: 2,
          strIngredient3Id: 3,
          strIngredient4Id: null,
          strIngredient5Id: null,
          strIngredient6Id: null,
          strIngredient7Id: null,
          strIngredient8Id: null,
          strIngredient9Id: null,
          strIngredient10Id: null,
          strIngredient11Id: null,
          strIngredient12Id: null,
          strIngredient13Id: null,
          strIngredient14Id: null,
          strIngredient15Id: null,
          strIngredient16Id: null,
          strIngredient17Id: null,
          strIngredient18Id: null,
          strIngredient19Id: null,
          strIngredient20Id: null,
          strMeasure1: 'Dash',
          strMeasure2: '1 Can',
          strMeasure3: '5 thin cut',
          strMeasure4: null,
          strMeasure5: null,
          strMeasure6: null,
          strMeasure7: null,
          strMeasure8: null,
          strMeasure9: null,
          strMeasure10: null,
          strMeasure11: null,
          strMeasure12: null,
          strMeasure13: null,
          strMeasure14: null,
          strMeasure15: null,
          strMeasure16: null,
          strMeasure17: null,
          strMeasure18: null,
          strMeasure19: null,
          strMeasure20: null,
          strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
          strImageSource: null,
          strCreativeCommonsConfirmed: null,
          dateModified: null,
        },
      ],
      {},
    );
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete('meals', {});
  },
};
