export interface IRecipes {
  strDrinkAlternate: string | null;
  strCategoryId: number;
  strTags: string;
  strIngredient1Id: number;
  strIngredient2Id: number;
  strIngredient3Id: number;
  strIngredient4Id: number;
  strIngredient5Id: number;
  strIngredient6Id: number;
  strIngredient7Id: number;
  strIngredient8Id: number;
  strIngredient9Id: number;
  strIngredient10Id: number;
  strIngredient11Id: number;
  strIngredient12Id: number;
  strIngredient13Id: number;
  strIngredient14Id: number;
  strIngredient15Id: number;
  strMeasure1: string | null;
  strMeasure2: string | null;
  strMeasure3: string | null;
  strMeasure4: string | null;
  strMeasure5: string | null;
  strMeasure6: string | null;
  strMeasure7: string | null;
  strMeasure8: string | null;
  strMeasure9: string | null;
  strMeasure10: string | null;
  strMeasure11: string | null;
  strMeasure12: string | null;
  strMeasure13: string | null;
  strMeasure14: string | null;
  strMeasure15: string | null;
  strImageSource: string | null;
  strCreativeCommonsConfirmed: string | null;
  dateModified: string | null;
}
